services:
  app:
    build:
      context: .
    environment:
      LOG_LEVEL: debug
      LOG_IS_DEVELOPMENT: true
      KEYCLOAK_ENDPOINT: http://keycloak:8080
      KEYCLOAK_USERNAME: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGIN_REALM: master
      KEYCLOAK_USER_REALM: koken
      KEYCLOAK_MEMBER_GROUP_NAME: koken
      KEYCLOAK_ATTRS_KEY: discord-username
      KEYCLOAK_GROUP_PATH: /koken
      DISCORD_TOKEN: MTA2MzgyNDUyMjQ1ODk1NTc5OA.G_Ph6L.qY-30izo1kr0q9JW5i3LjRxMOGc8P-lGurCzxY
      DISCORD_GUILD_ID: 829681869707935774
      DISCORD_ROLE_ID: 1063825231485096056
    depends_on:

      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      retries: 10
    ports:
      - 8080:8080
  keycloak-db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
